### ISSUE TITLE
PictureProcess

### ISSUE THREAD

**Issue by Yousanflics** [amidmajd/pic_proc_huffmanCompress#1]
Hey dude can you explain the principle of jpg picture process you used in this project? thx!

**Comment by amidmajd** [comment]
hi
basically, jpg is a compressed image format and every pixel is a 3-dimensional vector which is (red, green, blue) (RGB)  or (x,y,z)
but my script is based on gray images that every pixel is a number between 0 to 255 or (x,x,x)
my project accepts RGB images and converts them to gray image then process them and ...
